apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-scheduling-service2
  labels:
    app: appointment-scheduling-service2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1          
      maxUnavailable: 1    
  selector:
    matchLabels:
      app: appointment-scheduling-service2
  template:
    metadata:
      labels:
        app: appointment-scheduling-service2
    spec:
      containers:
      - name: appointment-scheduling-service2
        image: 891612584112.dkr.ecr.us-east-2.amazonaws.com/appointment-scheduling-service2:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
