apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-scheduling-service
  labels:
    app: appointment-scheduling-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-scheduling-service
  template:
    metadata:
      labels:
        app: appointment-scheduling-service
    spec:
      containers:
      - name: appointment-scheduling-service
        image: 891612584112.dkr.ecr.us-east-1.amazonaws.com/appointment-scheduling-service:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
