apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service
  labels:
    app: patient-record-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-record-service
  template:
    metadata:
      labels:
        app: patient-record-service
    spec:
      containers:
      - name: patient-record-service
        image: 891612584112.dkr.ecr.us-east-1.amazonaws.com/patient-record-service:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
