apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1          # Allows one extra pod above the replica count during updates
      maxUnavailable: 1    # Allows one pod to be unavailable during updates
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: 891612584112.dkr.ecr.us-east-1.amazonaws.com/notification-service:${{ github.sha }}
        ports:
        - containerPort: 8080
